### PR TITLE
followanalytics/fa-issues/issues/10016

### PR DESCRIPTION
**Pull request by Cephaz**
Relate to followanalytics/fa-issues/issues/10016

### CODE REVIEW

**Review by firedeathz — APPROVED** [review]

**Comment by firedeathz** [comment]
@Cephaz Can you generate the .zip files locally for each template please? 
First you need to update the version of each template manually, by going into the `definition.json` file and incrementing the version (tertiary number in this case) by 1 (i.e 2.0.1 -> 2.0.2).

Afterwards, to get the zip files, you can run the following command(s):
```
npm run install-all   (if you haven't installed npm packages yet, for each template)
npm run build-all
```

Lastly, you will need to upload these new zip files on the google drive folder we have for them. Link is here: https://drive.google.com/drive/folders/1xsyN3yFLUpY1Hn9QGwu_SS7V2Q87KXg8
If you do not have access to the folder, please ask @jjoaquim for it (I assume he can give you access, since Hajar is not here).

**Comment by Cephaz** [comment]
Update files in the drive, do you want me to send the latest version? @firedeathz

**Comment by jjoaquim** [comment]
@Cephaz is it good now?

**Comment by Cephaz** [comment]
Yes I added in the Drive @jjoaquim

**Comment by Cephaz** [comment]
Should I change the version of the template on this repository?

**Comment by diego-souza** [comment]
@firedeathz What is the status of this PR? It looks like a typo fix. Should we merge it?
I moved the ticket https://github.com/followanalytics/fa-issues/issues/10016 into Ready To Test on the new workspace. Ana Maria said she'll test it before closing the ticket.

**Comment by firedeathz** [comment]
We can merge this PR already (actually dunno why it's still not merged, since we've made the zip files available already)

**Pull request merged**
